apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stocks
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cloudacademy/stocks-app-gitops.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudacademy