apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: cloudacademy
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: cloudacademydevops/stocks-db:latest
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: fo11owth3wh1t3r4bb1t
        ports:
        - containerPort: 3306
          name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: cloudacademy
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None